workflow:
  rules:
    # Ignore pipeline for filthy commits
#    - if: $CI_COMMIT_MESSAGE =~ /^wip.*/i
#      when: never
    # Execute for MR, but avoid duplicated due to branch triggers in MR
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    # Else execute on tags or default branch
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  auto_cancel:
    on_new_commit: interruptible

stages:
  - Build
  - Static Analysis
  - Documentation
  - Test
  - Applications Test
  - Ship

variables:
  OTBTF_VERSION: 5.0.0rc4
  OTBTF_SRC: /src/otbtf  # OTBTF source directory path in image
  DATADIR: $CI_PROJECT_DIR/test/data
  CACHE_IMAGE_CPU: $CI_REGISTRY_IMAGE:build-cache-cpu
  CACHE_IMAGE_GPU: $CI_REGISTRY_IMAGE:build-cache-gpu
  BRANCH_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  BUILDX_BUILDER: container
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1
  CI_REGISTRY_PUBIMG: $CI_REGISTRY_IMAGE:$OTBTF_VERSION
  IMAGE_CPU: $CI_REGISTRY_PUBIMG-cpu
  IMAGE_CPUDEV: $CI_REGISTRY_PUBIMG-cpu-dev
  IMAGE_GPU: $CI_REGISTRY_PUBIMG-gpu
  IMAGE_GPUDEV: $CI_REGISTRY_PUBIMG-gpu-dev

default:
  tags: [ godzilla ]
  interruptible: true
  image:
    name: $BRANCH_IMAGE
    pull_policy: always

.docker_build_base:
  image: docker:27.5.1
  services:
    - name: docker:27.5.1-dind
  before_script:
    - echo -n "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker buildx create --name=container --driver=docker-container --use --bootstrap
  after_script:
    - docker buildx rm --keep-state container

docker_image:
  stage: Build
  only:
    - merge_requests
    - develop
  extends: .docker_build_base
  script:
    - >
      docker buildx build --push -t $BRANCH_IMAGE
      --cache-from type=registry,ref=$CACHE_IMAGE_CPU
      --cache-to type=registry,ref=$CACHE_IMAGE_CPU,mode=max
      --build-arg DEV_IMAGE=true
      "."

.static_analysis_base:
  stage: Static Analysis
  allow_failure: true
  only:
    - merge_requests

flake8:
  extends: .static_analysis_base
  script:
    - flake8 $OTBTF_SRC/otbtf --exclude=tensorflow_v1x

pylint:
  extends: .static_analysis_base
  script:
    - pylint $OTBTF_SRC/otbtf --ignore=tensorflow_v1x

codespell:
  rules:
  extends: .static_analysis_base
  script:
    - codespell otbtf doc README.md

cppcheck:
  extends: .static_analysis_base
  script:
    - cd $OTBTF_SRC/ && cppcheck --enable=all --error-exitcode=1 -I include/ --suppress=missingInclude --suppress=unusedFunction .

docs:
  stage: Documentation
  tags: [ stable ]
  needs: []
  image: python:3.10-slim
  variables:
    PTH: public_test
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_REF_NAME == /master/
      variables:
        PTH: public
    - changes:
      - doc/**/*
      - "*.{md,txt}"
      - mkdocs.yml
      - .readthedocs.yaml
  before_script:
    - pip install -r doc/doc_requirements.txt
  script:
    - mkdocs build --site-dir $PTH
  artifacts:
    paths:
      - public
      - public_test

ctest:
  stage: Test
  variables:
    CTEST_OUTPUT_ON_FAILURE: 1
    OTB_TEST_UNITS: "Tensorflow|PanSharpening|Projection|Transform|IOGDAL"
    OTB_BUILD: /src/otb/build/OTB/build
  script:
    - cd /src/otb/otb && git lfs pull
    - ln -s $CI_PROJECT_DIR/test/data $OTBTF_SRC/test/data
    - ln -s $CI_PROJECT_DIR/test/models $OTBTF_SRC/test/models
    - cd $OTB_BUILD
    - ctest -L $OTB_TEST_UNITS --output-junit $CI_PROJECT_DIR/report_ctest.xml
  after_script:
    - mv $OTB_BUILD/Testing/Temporary $CI_PROJECT_DIR/artifacts_ctest
  artifacts:
    reports:
      junit: report_ctest.xml
    paths:
      - artifacts_ctest
    expire_in: 4 weeks
    when: on_failure

python_api:
  stage: Test
  variables:
    API_TEST_TMP: /tmp/api_tests_tmp
  script:
    - mkdir $API_TEST_TMP
    - TMPDIR=$API_TEST_TMP python -m pytest -svv --junitxml=report_api.xml test/api_unittest.py
  after_script:
    - saved_model_cli show --dir $API_TEST_TMP/model_from_pimg --all
    - mv $API_TEST_TMP $CI_PROJECT_DIR/artifacts_test_api
  artifacts:
    reports:
      junit: report_python_api.xml
    paths:
      - artifacts_python_api
    expire_in: 4 weeks
    when: on_failure

.applications_test_base:
  stage: Applications Test
  needs: ["ctest", "python_api"]
  #when: manual
  only:
    - merge_requests
  artifacts:
    reports:
      junit: report_*.xml

crc_book:
  extends: .applications_test_base
  when: manual
  allow_failure: true
  variables:
    CRC_BOOK_TMP: /tmp/crc_book_tests_tmp
  script:
    - mkdir -p $CRC_BOOK_TMP
    - TMPDIR=$CRC_BOOK_TMP python -m pytest -v --junitxml=report_tutorial.xml test/tutorial_unittest.py
  after_script:
    - mv $CRC_BOOK_TMP $CI_PROJECT_DIR/artifacts_crc_book
  artifacts:
    reports:
      junit: report_tutorial.xml
    paths:
      - artifacts_crc_book
    expire_in: 4 weeks
    when: on_failure

decloud:
  extends: .applications_test_base
  when: manual
  allow_failure: true
  variables:
    DATASET_DECLOUD: https://nextcloud.inrae.fr/s/aNTWLcH28zNomqk/download
    DECLOUD_DATA_DIR: $CI_PROJECT_DIR/decloud_data
  script:
    - git clone https://forgemia.inra.fr/umr-tetis/decloud.git -b keras3
    - pip install -r $PWD/decloud/requirements.txt
    - wget -q $DATASET_DECLOUD -O file.zip && unzip file.zip
    - pytest -v --junitxml=report_decloud.xml decloud/tests/train_from_tfrecords_unittest.py

sr4rs:
  extends: .applications_test_base
  variables:
    DATASET_S2: https://nextcloud.inrae.fr/s/EZL2JN7SZyDK8Cf/download/sr4rs_sentinel2_bands4328_france2020_savedmodel.zip
    DATASET_SR4RS: https://nextcloud.inrae.fr/s/kDms9JrRMQE2Q5z/download
  script:
    - wget -qO sr4rs_sentinel2_bands4328_france2020_savedmodel.zip $DATASET_S2
    - unzip -o sr4rs_sentinel2_bands4328_france2020_savedmodel.zip
    - wget -qO sr4rs_data.zip $DATASET_SR4RS
    - unzip -o sr4rs_data.zip
    - rm -rf sr4rs
    - git clone https://github.com/remicres/sr4rs.git
    - export PYTHONPATH=$PYTHONPATH:$PWD/sr4rs
    - pytest -v --junitxml=report_sr4rs.xml test/sr4rs_unittest.py

geos_enabled:
  extends: .applications_test_base
  script:
    - python -m pytest -v --junitxml=report_geos_enabled.xml test/geos_test.py

planetary_computer:
  extends: .applications_test_base
  script:
    - pip install pystac_client planetary_computer
    - python -m pytest -v --junitxml=report_pc_enabled.xml test/pc_test.py

numpy_gdal_otb:
  extends: .applications_test_base
  script:
    - python -m pytest -v --junitxml=report_numpy.xml test/numpy_test.py

rio:
  extends: .applications_test_base
  script:
    - pip install rasterio --no-binary rasterio
    - python -m pytest -v --junitxml=report_rio.xml test/rio_test.py

nodata:
  extends: .applications_test_base
  script:
    - python -m pytest -v --junitxml=report_nodata.xml test/nodata_test.py

ship_gitlab:
  stage: Ship
  extends: .docker_build_base
  needs: ["ctest", "python_api"]
  retry: 2
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - echo -n "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker buildx create --name=container --driver=docker-container --use --bootstrap
  script:
    # CPU
    - >
      docker buildx build --push -t $IMAGE_CPUDEV
      --cache-from type=registry,ref=$CACHE_IMAGE_CPU
      --build-arg DEV_IMAGE=true
      .
    - >
      docker buildx build --push -t $IMAGE_CPU
      --cache-from type=registry,ref=$CACHE_IMAGE_CPU
      .
    # GPU
    - >
      docker buildx build --push -t $IMAGE_GPUDEV
      --cache-from type=registry,ref=$CACHE_IMAGE_GPU
      --cache-to type=registry,ref=$CACHE_IMAGE_GPU,mode=max
      --build-arg WITH_CUDA=true --build-arg DEV_IMAGE=true
      .
    - >
      docker buildx build --push -t $IMAGE_GPU
      --cache-from type=registry,ref=$CACHE_IMAGE_GPU
      --build-arg WITH_CUDA=true
      .

ship_dockerhub:
  stage: Ship
  extends: .docker_build_base
  needs: ["ship_gitlab"]
  retry: 2
  rules:
    # Match release tag e.g. 5.0.0, skip for rc or any suffix
    - if: $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+$/
  variables:
    DOCKERHUB_BASE: mdl4eo/otbtf
    DOCKERHUB_IMAGE_BASE: $DOCKERHUB_BASE:$OTBTF_VERSION
  before_script:
    - echo -n "$DOCKERHUB_TOKEN" | docker login -u mdl4eo --password-stdin
  script:
    # CPU
    - docker pull $IMAGE_CPU
    - docker tag $IMAGE_CPU $DOCKERHUB_IMAGE_BASE-cpu && docker push $DOCKERHUB_IMAGE_BASE-cpu
    - docker pull $IMAGE_CPUDEV
    - docker tag $IMAGE_CPUDEV $DOCKERHUB_IMAGE_BASE-cpu-dev && docker push $DOCKERHUB_IMAGE_BASE-cpu-dev
    - docker tag $IMAGE_CPU $DOCKERHUB_BASE:latest && docker push $DOCKERHUB_BASE:latest
    # GPU
    - docker pull $IMAGE_GPU
    - docker tag $IMAGE_GPU $DOCKERHUB_IMAGE_BASE-gpu && docker push $DOCKERHUB_IMAGE_BASE-gpu
    - docker pull $IMAGE_GPUDEV
    - docker tag $IMAGE_GPUDEV $DOCKERHUB_IMAGE_BASE-gpu-dev && docker push $DOCKERHUB_IMAGE_BASE-gpu-dev
    - docker tag $IMAGE_GPU $DOCKERHUB_BASE:latest-gpu && docker push $DOCKERHUB_BASE:latest-gpu
