variables:
  OTBTF_VERSION: 4.4.0
  OTB_BUILD: /src/otb/build/OTB/build  # Local OTB build directory
  OTBTF_SRC: /src/otbtf  # Local OTBTF source directory
  OTB_TEST_DIR: $OTB_BUILD/Testing/Temporary  # OTB testing directory
  ARTIFACT_TEST_DIR: $CI_PROJECT_DIR/testing
  CRC_BOOK_TMP: /tmp/crc_book_tests_tmp
  API_TEST_TMP: /tmp/api_tests_tmp
  DATADIR: $CI_PROJECT_DIR/test/data
  DOCKER_BUILDKIT: 1
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1
  BUILDX_BUILDER: container
  DOCKER_DRIVER: overlay2
  CACHE_IMAGE_CPU: $CI_REGISTRY_IMAGE:build-cache-cpu
  CACHE_IMAGE_GPU: $CI_REGISTRY_IMAGE:build-cache-gpu
  BRANCH_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  DEV_IMAGE: $CI_REGISTRY_IMAGE:cpu-basic-dev-testing
  CI_REGISTRY_PUBIMG: $CI_REGISTRY_IMAGE:$OTBTF_VERSION
  DOCKERHUB_BASE: mdl4eo/otbtf
  DOCKERHUB_IMAGE_BASE: ${DOCKERHUB_BASE}:${OTBTF_VERSION}

workflow:
  auto_cancel:
    on_new_commit: interruptible
  rules:
    # Execute jobs in merge request context, or commit in master branch
    - if: $CI_MERGE_REQUEST_ID || $CI_COMMIT_REF_NAME =~ /master/
    # Ignore pipeline for filthy commits
    - if: $CI_COMMIT_MESSAGE =~ /^wip.*/i
      when: never

default:
  interruptible: true
  image:
    name: $BRANCH_IMAGE
    pull_policy: always

stages:
  - Build
  - Static Analysis
  - Documentation
  - Test
  - Applications Test
  - Update dev image
  - Ship
  - Export TF wheels

.docker_build_base:
  tags: [ godzilla ]
  image: docker:latest
  services:
    - name: docker:dind
  before_script:
    - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker buildx create --name container --driver=docker-container

docker_image:
  stage: Build
  extends: .docker_build_base
  script:
    - >
      docker buildx build --push -t $BRANCH_IMAGE
      --cache-from type=registry,ref=$CACHE_IMAGE_CPU
      --cache-to type=registry,ref=$CACHE_IMAGE_CPU,mode=max,oci-mediatypes=true,image-manifest=true
      --build-arg DEV_IMAGE=true --build-arg OTBTESTS=true
      "."

.static_analysis_base:
  tags: [ stable ]
  stage: Static Analysis
  allow_failure: true

flake8:
  extends: .static_analysis_base
  script:
    - flake8 $OTBTF_SRC/otbtf --exclude=tensorflow_v1x

pylint:
  extends: .static_analysis_base
  script:
    - pylint $OTBTF_SRC/otbtf --ignore=tensorflow_v1x

codespell:
  extends: .static_analysis_base
  script:
    - codespell otbtf
    - codespell doc

cppcheck:
  extends: .static_analysis_base
  script:
    - cd $OTBTF_SRC/ && cppcheck --enable=all --error-exitcode=1 -I include/ --suppress=missingInclude --suppress=unusedFunction .

.doc_base:
  tags: [ stable ]
  image: python:3.10-slim
  stage: Documentation
  before_script:
    - pip install -r doc/doc_requirements.txt
  artifacts:
    paths:
      - public
      - public_test

pages_test:
  extends: .doc_base
  only:
    changes:
      - doc/*
      - mkdocs.yml
      - .readthedocs.yaml
  except:
    - master
  script:
    - mkdocs build --site-dir public_test

pages:
  extends: .doc_base
  only:
    - master
  script:
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public

.tests_base:
  artifacts:
    paths:
      - $ARTIFACT_TEST_DIR/*.*
    expire_in: 1 week
    when: on_failure

ctest:
  tags: [ godzilla ]
  extends: .tests_base
  stage: Test
  script:
    - cd /src/otb/otb && git lfs fetch --all && git lfs pull
    - ln -s $(pwd)/test/data /src/otbtf/test/data
    - ln -s $(pwd)/test/models /src/otbtf/test/models
    - cd $OTB_BUILD/
    - ctest -L OTBTensorflow
    - ctest -L OTBPanSharpening
    - ctest -L OTBProjection
    - ctest -L OTBTransform
    - ctest -L OTBIOGDAL
  after_script:
    - cp -r $OTB_TEST_DIR $ARTIFACT_TEST_DIR

.applications_test_base:
  tags: [ goldenrunner ]
  extends: .tests_base
  #rules:
  #  - if: $CI_MERGE_REQUEST_ID
  #    when: manual
  stage: Applications Test
  before_script:
    - mkdir -p $ARTIFACT_TEST_DIR
    - cd $CI_PROJECT_DIR

crc_book:
  extends: .applications_test_base
  script:
    - mkdir -p $CRC_BOOK_TMP
    - TMPDIR=$CRC_BOOK_TMP python -m pytest --junitxml=$CI_PROJECT_DIR/report_tutorial.xml test/tutorial_unittest.py
  after_script:
    - cp $CRC_BOOK_TMP/*.* $ARTIFACT_TEST_DIR/
    
sr4rs:
  extends: .applications_test_base
  script:
    - wget -O sr4rs_sentinel2_bands4328_france2020_savedmodel.zip
      https://nextcloud.inrae.fr/s/EZL2JN7SZyDK8Cf/download/sr4rs_sentinel2_bands4328_france2020_savedmodel.zip
    - unzip -o sr4rs_sentinel2_bands4328_france2020_savedmodel.zip
    - wget -O sr4rs_data.zip https://nextcloud.inrae.fr/s/kDms9JrRMQE2Q5z/download
    - unzip -o sr4rs_data.zip
    - rm -rf sr4rs
    - git clone https://github.com/remicres/sr4rs.git
    - export PYTHONPATH=$PYTHONPATH:$PWD/sr4rs
    - python -m pytest --junitxml=$ARTIFACT_TEST_DIR/report_sr4rs.xml test/sr4rs_unittest.py

decloud:
  extends: .applications_test_base
  script:
    - git clone https://github.com/CNES/decloud.git
    - pip install -r $PWD/decloud/docker/requirements.txt
    - wget https://nextcloud.inrae.fr/s/aNTWLcH28zNomqk/download -O file.zip && unzip file.zip
    - export DECLOUD_DATA_DIR="$PWD/decloud_data"
    - pytest decloud/tests/train_from_tfrecords_unittest.py

otbtf_api:
  extends: .applications_test_base
  script:
    - mkdir $API_TEST_TMP
    - TMPDIR=$API_TEST_TMP python -m pytest --junitxml=$ARTIFACT_TEST_DIR/report_api.xml test/api_unittest.py
  after_script:
    - cp $API_TEST_TMP/*.* $ARTIFACT_TEST_DIR/

geos_enabled:
  extends: .applications_test_base
  script:
    - python -m pytest --junitxml=$ARTIFACT_TEST_DIR/report_geos_enabled.xml test/geos_test.py

planetary_computer:
  extends: .applications_test_base
  script:
    - pip install pystac_client planetary_computer
    - python -m pytest --junitxml=$ARTIFACT_TEST_DIR/report_pc_enabled.xml test/pc_test.py

imports:
  extends: .applications_test_base
  script:
    - python -m pytest --junitxml=$ARTIFACT_TEST_DIR/report_imports.xml test/imports_test.py

numpy_gdal_otb:
  extends: .applications_test_base
  script:
    - python -m pytest --junitxml=$ARTIFACT_TEST_DIR/report_numpy.xml test/numpy_test.py

rio:
  extends: .applications_test_base
  script:
    - pip install rasterio --no-binary rasterio
    - python -m pytest --junitxml=$ARTIFACT_TEST_DIR/report_rio.xml test/rio_test.py

nodata:
  extends: .applications_test_base
  script:
    - python -m pytest --junitxml=$ARTIFACT_TEST_DIR/report_nodata.xml test/nodata_test.py

.ship_base:
  extends: .docker_build_base
  stage: Ship
  only:
    - master

deploy_cpu:
  extends: .ship_base
  variables:
    IMAGE_CPU: $CI_REGISTRY_PUBIMG-cpu
    IMAGE_CPUDEV: $CI_REGISTRY_PUBIMG-cpu-dev
    DOCKERHUB_CPU: $DOCKERHUB_IMAGE_BASE-cpu
    DOCKERHUB_CPUDEV: $DOCKERHUB_IMAGE_BASE-cpu-dev
    DOCKERHUB_LATEST: $DOCKERHUB_BASE:latest
  script:
    # cpu
    - >
      docker buildx build --push -t $IMAGE_CPU
      --cache-from type=registry,ref=$CACHE_IMAGE_CPU
      .
    # cpu-dev
    - >
      docker buildx build --push -t $IMAGE_CPUDEV
      --cache-from type=registry,ref=$CACHE_IMAGE_CPU
      --build-arg DEV_IMAGE=true
      .
    # push images on dockerhub
    - echo -n $DOCKERHUB_TOKEN | docker login -u mdl4eo --password-stdin
    - docker tag $IMAGE_CPU $DOCKERHUB_CPU && docker push $DOCKERHUB_CPU
    - docker tag $IMAGE_CPUDEV $DOCKERHUB_CPUDEV && docker push $DOCKERHUB_CPUDEV
    # latest = cpu image
    - docker tag $IMAGE_CPU $DOCKERHUB_LATEST && docker push $DOCKERHUB_LATEST

deploy_gpu:
  extends: .ship_base
  variables:
    IMAGE_GPU: $CI_REGISTRY_PUBIMG-gpu
    IMAGE_GPUDEV: $CI_REGISTRY_PUBIMG-gpu-dev
    DOCKERHUB_GPU: $DOCKERHUB_IMAGE_BASE-gpu
    DOCKERHUB_GPUDEV: $DOCKERHUB_IMAGE_BASE-gpu-dev
    DOCKERHUB_GPULATEST: $DOCKERHUB_BASE:latest-gpu
  script:
    # gpu
    - >
      docker buildx build --push -t $IMAGE_GPU
      --cache-from type=registry,ref=$CACHE_IMAGE_CPU
      --cache-from type=registry,ref=$CACHE_IMAGE_GPU
      --cache-to type=registry,ref=$CACHE_IMAGE_GPU,mode=max,oci-mediatypes=true,image-manifest=true
      --build-arg WITH_CUDA=true
      .
    # gpu-dev
    - >
      docker buildx build --push -t $IMAGE_GPUDEV
      --cache-from type=registry,ref=$CACHE_IMAGE_CPU
      --cache-from type=registry,ref=$CACHE_IMAGE_GPU
      --build-arg WITH_CUDA=true --build-arg DEV_IMAGE=true
      .
    # push gpu-* images on dockerhub
    - echo -n $DOCKERHUB_TOKEN | docker login -u mdl4eo --password-stdin
    - docker tag $IMAGE_GPU $DOCKERHUB_GPU && docker push $DOCKERHUB_GPU
    - docker tag $IMAGE_GPUDEV $DOCKERHUB_GPUDEV && docker push $DOCKERHUB_GPUDEV
    # latest-gpu = gpu image
    - docker tag $IMAGE_GPU $DOCKERHUB_GPULATEST && docker push $DOCKERHUB_GPULATEST

export_tf_wheels:
  extends: .docker_build_base
  stage: Export TF wheels
  rules:
    - when: manual
  artifacts:
    paths:
      - cpu-build-artifacts/
      - gpu-build-artifacts/
  script:
    # cpu
    - >
      docker buildx build --target=tf-build
      --mount=type=bind,source=$(pwd)/cpu-build-artifacts,target=/tmp/artifacts
      --build-arg TF_BUILD_ARTIFACTS=/tmp/artifacts
      --cache-from type=registry,ref=$CACHE_IMAGE_CPU
      .
    # gpu
    - >
      docker buildx build --target=tf-build
      --mount=type=bind,source=$(pwd)/gpu-build-artifacts,target=/tmp/artifacts
      --build-arg WITH_CUDA=true
      --build-arg TF_BUILD_ARTIFACTS=/tmp/artifacts
      --cache-from type=registry,ref=$CACHE_IMAGE_GPU
      .
